"use client";

import React, { useState, useEffect } from "react";
import { useWorkspace } from "../../context/WorkspaceContext";
import { Sparkles, X, Copy } from "lucide-react";

interface ParsedIntentModalProps {
  isOpen: boolean;
  onClose: () => void;
  refinedText: string;
}

export default function ParsedIntentModal({
  isOpen,
  onClose,
  refinedText,
}: ParsedIntentModalProps) {
  const { setInput } = useWorkspace();
  const [editedText, setEditedText] = useState(refinedText);

  // Update edited text when a new generation comes in
  useEffect(() => {
    setEditedText(refinedText);
  }, [refinedText]);

  if (!isOpen) return null;

  const handleApply = () => {
    setInput(editedText);
    onClose();
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(editedText);
      // Optional: Add a toast notification here
    } catch (err) {
      console.error("Failed to copy text: ", err);
    }
  };

  return (
    <div 
      className="fixed inset-0 z-[100] flex items-center justify-center p-4 md:p-6 bg-slate-950/40 backdrop-blur-sm transition-all duration-300"
      onClick={onClose}
    >
      <div 
        className="w-full max-w-2xl bg-[#0a1118]/90 border border-white/10 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh] md:max-h-[80vh] glass-panel-dark animate-in fade-in zoom-in duration-200"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="p-5 border-b border-white/5 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="bg-cyan-500/20 p-2 rounded-lg text-cyan-400">
              <Sparkles className="size-5" />
            </div>
            <div>
              <h2 className="text-white font-bold tracking-tight">Refined Prompt</h2>
              <p className="text-xs text-slate-400 font-medium">Generated by Gemini Engine</p>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="text-slate-400 hover:text-white transition-colors"
          >
            <X className="size-5" />
          </button>
        </div>

        {/* Content Area */}
        <div className="flex-1 p-5 overflow-y-auto">
          <div className="relative group">
            <div className="absolute -inset-0.5 bg-gradient-to-r from-cyan-500/20 to-primary/20 rounded-xl blur opacity-50 group-hover:opacity-100 transition duration-500" />
            <textarea
              value={editedText}
              onChange={(e) => setEditedText(e.target.value)}
              className="relative w-full h-[300px] md:h-[400px] bg-black/40 border border-white/10 rounded-xl p-4 text-slate-200 text-sm md:text-base leading-relaxed focus:outline-none focus:ring-1 focus:ring-cyan-500/50 resize-none font-sans"
              placeholder="Refined prompt will appear here..."
            />
          </div>
        </div>

        {/* Footer Actions */}
        <div className="p-5 bg-white/5 flex flex-col sm:flex-row gap-3 items-center justify-between">
          <button
            onClick={handleCopy}
            className="flex items-center gap-2 text-slate-400 hover:text-white transition-colors text-sm font-medium px-2 py-1"
          >
            <Copy className="size-5" />
            Copy to Clipboard
          </button>
          
          <div className="flex items-center gap-3 w-full sm:w-auto">
            <button
              onClick={onClose}
              className="flex-1 sm:flex-none px-6 py-2.5 rounded-xl border border-white/10 text-slate-300 font-bold text-sm hover:bg-white/5 transition-all"
            >
              Discard
            </button>
            <button
              onClick={handleApply}
              className="flex-1 sm:flex-none px-6 py-2.5 rounded-xl bg-gradient-to-r from-cyan-500 to-primary text-white font-bold text-sm shadow-neon hover:shadow-neon-strong transition-all transform hover:-translate-y-0.5"
            >
              Use as Input
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
